### ISSUE TITLE
Release v0.4

### ISSUE THREAD

**Issue by PHoNX123** [farfilli/SolidEdge-Voronoi#2]
First of all, thanks for your work. It great to available here. 

I have two comments : 

1. When I dowload and run the latest Release is indicated 0.3 instead of 0.4.
2. The gnerator is pretty slow. Its possible to set up the desired location of the generated voronoi sketch? 

Thanks for your help. :)

**Comment by PHoNX123** [comment]
Here is the generated diagram:

![image](https://github.com/farfilli/SolidEdge-Voronoi/assets/103641752/c533563c-5ad4-4448-af59-5e018fffc12b)

And here is the drawed one in SE:

![image](https://github.com/farfilli/SolidEdge-Voronoi/assets/103641752/dd1584ef-2138-4a3e-a477-860506788bd4)

**Comment by farfilli** [comment]
Thanks for the comment; I just released v.0.5 where the Draw in SE performance is fixed; it draw almost instantly on my test case with 200 points.
The version on the title wasn't updated by mistake on v0.4; v0.5 is ok now

About the ability to select a location I have to think about how to introduce it; since a user may want to move, rotate, or scale the diagram by now I prefer to leave the user to do it directly on Solid Edge. It may help to group all the entities but it could be a slowdown for subsequent usage, feel free to give feedback on this.

Also, screenshot of usage of the diagram in products are very welcome, if you send me any I will add them to the "gallery"
